#!/bin/bash

#
# Common variables
#

DDIFLOW_VERSION=0.0.1
DDIFLOW_REPO=https://github.com/kulerskim/ddiflow

# loading settings that can be overridden using git config
ddiflow_load_settings() {
  export JIRA_ADDRESS=$(git config --get jira.address)
  export JIRA_USERNAME=$(git config --get jira.username)
  export JIRA_AUTH=$(git config --get jira.auth)
}

ddiflow_extract_issue() {
  issue=`echo "$1" | sed -e 's/.*-\([a-zA-Z]\+-[0-9]\+\)/\1/'`
  if [ "$issue" == "$1" ]; then
    return 1
  fi
  echo $issue
}

ddiflow_issue_transition() {
  agile_toolbelt.rb jira transition $1 "$2"
  return $?
}
